extends State
class_name EnemyIdleState

@export var seek_radius := 1.0
@export var max_attempts := 12
#@export var wait_time := 0.4

var is_wandering : bool
var destination_picked : bool

#gets the intial global positon to set it as a waypoint so that the calculated rand_vector offset it from the 
#original global origin rather than the origin after already wandering 
#(im doing this to prevent the enemy from wandering too far off from the area they were initially placed/spawned in
#var initial_pos 
#^^ replaced this var with a var that is stored in the slime characterbody2d script

var initial_speed = 0
var initial_radius = 0

func enter() -> void:
	entity.sprite.play("Idle")
	#only ever sets the initial_pos once when the idle state is first called
	if entity.initial_global_pos == null:
		entity.initial_global_pos = entity.global_position
	#sets the pursue radius to whatever was set in the inspector 
	entity.pursueRadius.get_node("CollisionShape2D").shape.radius = seek_radius
	#sets the wander radius to whatever the pursue raidus is too
	entity.wander_radius.get_node("CollisionShape2D").shape.radius = seek_radius
	#set is_wandering to false by default
	is_wandering = false

	
	#sets the wander_dir to zero on entering so that the check in physics process wont run until the timernode is done
	entity.wander_dir = Vector2.ZERO
	
	#starts the timer with the intial wait time that was set on the timer node
	entity.wander_wait_timer.start()
	
	#connects the area2d detection function
	entity.pursueRadius.body_entered.connect(_on_slime_pursue_radius_body_entered)

func exit() -> void:
	#stops the wander reset timer so that it doesnt continue to update even out of the state 
	entity.wander_wait_timer.stop()
	#disconnects the area2d detection function
	#entity.pursueRadius.body_entered.disconnect(_on_slime_pursue_radius_body_entered)

func update(_delta : float) -> void:
	#if the target has been picked then tranisiton to wander
	if entity.wander_dir == Vector2.ZERO:
		return
	else:
		Transitioned.emit(self, "Wander")
		
func physics_update(_delta: float) -> void:
	pass

func _on_wander_wait_timer_timeout() -> void:
	#sets the next wait length to a rand float 
	entity.wander_wait_timer.wait_time = randf_range(1.0, 3.0)
	
	#since the timer ran out, its time for the slime to wander 
	is_wandering = true
	
	#calls the function to run the logic to get the slimes direction
	_get_dir()

#returns an offset vector of the initial global pos
func _get_rand_vector() -> Vector2:
	var rand_angle = randf() * TAU
	var rand_radius = sqrt(randf()) * seek_radius
	var rand_vector = Vector2(cos(rand_angle), sin(rand_angle)) * rand_radius
	destination_picked = true
	return rand_vector

func _get_dir():
	#stores the global positon of the target generated by the random vector
	#intial global pos is added since rand_vector is just an offset of the local coords
	entity.wander_target_global = _get_rand_vector() + entity.initial_global_pos
	
	#sets the initial direction the slime is set to travel in
	entity.wander_dir = (entity.wander_target_global - entity.global_position).normalized()
	#sets the raycast to point to the position the slime is traveling to 
	#made local to the slime scene again since it is a child 
	entity.wander_raycast.target_position = entity.wander_target_global - entity.initial_global_pos
	


#if it detects the player enteres the pursue radius it switches to the pursue state
func _on_slime_pursue_radius_body_entered(body: Node2D) -> void:
	if body.is_in_group("Player"):
		#assigns the tracker vector to the detected players current position minus the enemies current 
		#position in order to find the proper global position and then normalizes it 
		entity.player_tracker = (body.global_position - entity.global_position).normalized()
		entity.testray.target_position = (body.global_position - entity.global_position)
		Transitioned.emit(self,"Pursue")
