extends CharacterBody2D


@onready var collision: CollisionShape2D = $CollisionShape2D
@onready var pursueRadius: Area2D = $SlimePursueRadius
@onready var wander_radius: Area2D = $WanderRadius
@onready var wander_wait_timer: Timer = $WanderWaitTimer
@onready var wander_raycast: RayCast2D = $WanderRaycast
@onready var sprite: AnimatedSprite2D = $Facing/AnimatedSprite2D
#added facing node2d in order to store all the nodes that i want to flip depending on where the enemy is facing
@onready var facing: Node2D = $Facing
@onready var testray: RayCast2D = $testray
#node to keep track of pursuit cooldown/reset
@onready var pursue_timer: Timer = $PursueTimer

#creates a duplicate of the slimes pursue radius resource
@onready var collision_dupe = self.pursueRadius.get_node("CollisionShape2D")

#var to track the enemy when they are detected to enter
var player_tracker: Vector2 = Vector2.ZERO

#store the glboal target that was randomly generated by the rand_vector function
var wander_target_global: Vector2 = Vector2.ZERO
#sets the direction that the slime needs to move in in order to reach the target
var wander_dir : Vector2 = Vector2.ZERO
var initial_global_pos = null

@export var enemy_speed = 100
@export var enemy_damage = 1

func _ready() -> void:	
	collision_dupe.shape = collision_dupe.shape.duplicate()
